### ISSUE TITLE
[컴퓨터 과학을 위한 수학] László Lovász의 강의노트 링크 수정 필요

### ISSUE THREAD

**Issue by ethan-sh-lee** [minnsane/TeachYourselfCS-KR#1]
기존 링크는 유효하지 않아서 원본에서 가져온 링크로 변경이 필요합니다.

기존 링크 : http://www.cs.elte.hu/~lovasz/dmbook.ps

원본에서 가져온 링크 : https://cims.nyu.edu/~regev/teaching/discrete_math_fall_2005/dmbook.pdf

**Comment by minnsane** [comment]
@sunho-lee 
감사합니다. 해당 링크는 업데이트 되었습니다!
